config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resource :dapp, only: [:show], controller: 'dapp'
  resource :account, only: [:show, :update], controller: 'account'
  resources :orders, only: [:create, :destroy, :update]
  resources :sell_orders, only: [:create]
  resources :deposits, only: [:create]
  resources :withdrawals, only: [:create]
  resources :token_deposits, only: [:create]
  resources :token_withdrawals, only: [:create]
  
  root to: 'dapp#show'
end

app/models/dapp/buy_order.rb
module Dapp
  class BuyOrder
    def initialize(transaction_hash:)
      @transaction_hash = transaction_hash
    end

    def run
      order = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Order').find_by_transaction_id(transaction_hash)
      Dapp::OrderDecorator.new(item: order).decorate
    end
    
    def description
      'placing your buy order'
    end

    private
  
    attr_reader :transaction_hash
  end
end

app/models/dapp/ether_deposit.rb
module Dapp
  class EtherDeposit
    def initialize(amount:)
      @amount = amount
      @function_name = 'depositEther'
    end
  
    def run
      return true
      transaction = build_transaction
      transaction.sign(key)
      BlOCKCHAIN_CLIENT.eth_send_raw_transaction(transaction.hex)
    end
    
    def description
      "depositing Ether"
    end

    private
  
    attr_reader :function_name, :amount
  
    def build_transaction
      Eth::Tx.new(tx_args)
    end
  
    def key
      Eth::Key.new priv: ENV['ACCOUNT_PRIVATE_KEY']
    end
  
    def tx_args
      {
        from: account,
        to: EXCHANGE.address,
        data: data,
        value: amount,
        nonce: BlOCKCHAIN_CLIENT.get_nonce(key.address),
        gas_limit: BlOCKCHAIN_CLIENT.gas_limit,
        gas_price: BlOCKCHAIN_CLIENT.gas_price
      }
    end
  
    def account
      BlOCKCHAIN_CLIENT.default_account
    end
  
    def function
      EXCHANGE.parent.functions.find { |f| f.name == function_name }
    end

    def data
      encoder = Ethereum::Encoder.new
      inputs = abi['inputs'].map { |input| OpenStruct.new(input) }
      input = encoder.encode_arguments(inputs, [])
      encoder.ensure_prefix(function.signature + input)
    end
  
    def abi
      EXCHANGE.abi.find { |abi| abi['name'] == function_name }
    end
  end
end

app/models/dapp/ether_withdraw.rb
module Dapp
  class EtherWithdraw
    def initialize(amount:)
      @amount = amount
    end

    def run
      EXCHANGE.transact_and_wait.withdraw_ether(amount)
    end
    
    def description
      "withdrawing Ether"
    end

    private
  
    attr_reader :amount
  end
end

app/models/dapp/graph.rb
module Dapp
  class Graph
    def initialize(orders:)
      @orders = orders
    end
    
    def last_price_change
      last_price >= second_last_price ? '+' : '-'
    end
    
    def last_price
      last_order.token_price
    end

    def series_data
      grouped_orders = orders.group_by{|o| o.formatted_timestamp.beginning_of_hour }
      Dapp::GraphDataBuilder.new(orders: grouped_orders).call
    end

    private
  
    attr_reader :orders

    def second_last_price
      second_last_order.token_price
    end
    
    def last_order
      orders.last
    end
    
    def second_last_order
      orders.slice(-2)
    end
  end
end

app/models/dapp/order_cancel.rb
module Dapp
  class OrderCancel
    def initialize(order_id:)
      @order_id = order_id
    end

    def run
      EXCHANGE.transact_and_wait.cancel_order(order_id)
    end
    
    def description
      "cancelling your order"
    end

    private
  
    attr_reader :order_id
  end
end

app/models/dapp/order_create.rb
module Dapp
  class OrderCreate
    def initialize(params:)
      @params = params
    end

    def run
      transaction = EXCHANGE.transact_and_wait.make_order(token_get, amount_get, token_give, amount_give)
      order = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Order').find_by_transaction_id(transaction.id)
      Dapp::OrderDecorator.new(item: order).decorate
    end

    private
  
    attr_reader :params
    
    def token_get
      TOKEN.address
    end
    
    def amount_get
      Ethereum::Formatter.new.to_wei(params[:buy_amount].to_i)
    end
    
    def token_give
      ENV['ETHER_ADDRESS']
    end
    
    def amount_give
      Ethereum::Formatter.new.to_wei(params[:buy_amount].to_i * params[:buy_price].to_f)
    end
  end
end

app/models/dapp/order_fill.rb
module Dapp
  class OrderFill
    def initialize(transaction_hash:, prev_token_price:)
      @transaction_hash = transaction_hash
      @prev_token_price = prev_token_price
    end

    def run
      trade = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Trade').find_by_transaction_id(transaction_hash)
      Dapp::TradeDecorator.new(item: trade, prev_token_price: prev_token_price).decorate
    end
    
    def description
      "filling your order"
    end

    private
  
    attr_reader :transaction_hash, :prev_token_price
  end
end

app/models/dapp/sell_order.rb
module Dapp
  class SellOrder
    def initialize(transaction_hash:)
      @transaction_hash = transaction_hash
    end

    def run
      order = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Order').find_by_transaction_id(transaction_hash)
      Dapp::OrderDecorator.new(item: order).decorate
    end
    
    def description
      'placing your sell order'
    end

    private
  
    attr_reader :transaction_hash
  end
end

app/models/dapp/status.rb
module Dapp
  class Status
      
    attr_reader :ether_balance, :exchange_ether_balance, :token_balance, :exchange_token_balance, :account
    
    def initialize()
      @account = current_account
      @ether_balance = current_ether_balance
      @exchange_ether_balance = current_exchange_ether_balance
      @token_balance = current_token_balance
      @exchange_token_balance = current_exchange_token_balance
    end
    
    private
    
    def current_ether_balance
      Ethereum::Formatter.new.from_wei(BlOCKCHAIN_CLIENT.eth_get_balance(account)['result'].hex)
    end
    
    def current_exchange_ether_balance
      Ethereum::Formatter.new.from_wei(EXCHANGE.call.balance_of(ENV['ETHER_ADDRESS'], account))
    end

    def current_token_balance
      TOKEN.call.balance_of(account)
    end
    
    def current_exchange_token_balance
      EXCHANGE.call.balance_of(TOKEN.address, account)
    end

    def current_account
      BlOCKCHAIN_CLIENT.default_account
    end
  end
end

app/models/dapp/token_deposit.rb
module Dapp
  class TokenDeposit
    def initialize(amount:)
      @amount = amount
    end

    def run
      TOKEN.transact_and_wait.approve(EXCHANGE.address, amount)
      EXCHANGE.transact_and_wait.deposit_token(TOKEN.address, amount)
    end
    
    def description
      "depositing Tokens"
    end

    private
  
    attr_reader :amount
  end
end

app/models/dapp/token_withdraw.rb
module Dapp
  class TokenWithdraw
    def initialize(amount:)
      @amount = amount
    end

    def run
      EXCHANGE.transact_and_wait.withdraw_token(TOKEN.address, amount)
    end
    
    def description
      "withdrawing Tokens"
    end

    private
  
    attr_reader :amount
  end
end

app/models/dapp/transaction_financials.rb
module Dapp
  class TransactionFinancials
    attr_reader :token_give, :amount_get, :amount_give

    def initialize(token_give:, amount_get:, amount_give:)
      @token_give = token_give
      @amount_get = amount_get
      @amount_give = amount_give
    end

    def ether_amount
      token_give_is_contract_address? ? amount_give : amount_get
    end
    
    def token_amount
      token_give_is_contract_address? ? amount_get : amount_give
    end

    def token_price
      price = (ether_amount.to_f / token_amount.to_f)
      (price * PRECISION).round / PRECISION.to_f
    end
    
    private
    
    def token_give_is_contract_address?
      token_give == ENV['ETHER_ADDRESS'] 
    end
  end
end

app/models/dapp/transactions_decorator.rb
module Dapp
  class TransactionsDecorator
    def initialize(items:, decorator:)
      @items = items
      @decorator = decorator
    end

    def decorate
      decorated_items = []
      items.each do |item|
        decorated_items << decorator.new(item: item).decorate
      end
      decorated_items
    end

    private

    attr_reader :items, :decorator
  end
end

app/controllers/dapp_controller.rb
class DappController < ApplicationController
  def show
    @dapp_status = Dapp::Status.new()

    exchange_trade_log = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Trade').call
    @trades = Dapp::TradesDecorator.new(items: exchange_trade_log).call
    
    exchange_order_log = Blockchain::Logs.new(contract: EXCHANGE, event_name: 'Order').call
    open_orders_log = Dapp::OpenOrdersQuery.new(orders: exchange_order_log).execute
    open_orders = Dapp::TransactionsDecorator.new(items: open_orders_log).call
    
    @sell_orders = open_orders.find_all{|o| o.order_type == 'sell'}
    @buy_orders = open_orders.find_all{|o| o.order_type == 'buy'}
    @my_orders = open_orders.find_all{|o| o.user.hex == @dapp_status.account.hex}
    @my_trades = @trades.find_all{|o| o.user.hex == @dapp_status.account.hex || o.user_fill.hex == @dapp_status.account.hex}
    
    @graph = Dapp::Graph.new(orders: @trades.sort_by(&:formatted_timestamp))
  end
end

app/helpers/dapp_helper.rb
module DappHelper
  def format_token_balance(val)
    precision = 100
    val = Ethereum::Formatter.new.from_wei(val).to_f.to_i
    val = (val * precision).round / precision
    val
  end
  
  def format_dapp_datetime(val)
    val.strftime("%l:%M:%S%P %e/%-m")
  end

  def buy_or_sell_color(val)
    val == "buy" ? 'text-success' : 'text-danger'
  end

  def price_symbol(last_price_change)
    if last_price_change == '+'
      content_tag :span, '&#9650;'.html_safe, class: 'text-success'
    else
      content_tag :span, '&#9660;'.html_safe,  class: 'text-danger'
    end
  end
end

app/views/dapp/balances/_balance.html.erb
<div class="vertical-split">
  <div class="card bg-dark text-white">
		<div class="card-header">Balance</div>
		<div id='dapp-balance-container'>
			<div id='dapp-balance' class="card-body">
			  <nav class="bg-dark text-white nav nav-tabs" role="tablist">
					<a href="#" role="tab"  data-bs-toggle="tab" data-bs-target="#deposit-form" aria-selected="true" class="nav-item nav-link active">Deposit</a>
					<a href="#" role="tab"  data-bs-toggle="tab" data-bs-target="#withdraw-form" aria-selected="false" class="nav-item nav-link">Withdraw</a>
				</nav>
				<div class="tab-content">
					<div id='deposit-form' role="tabpanel" aria-hidden="false" class="fade bg-dark tab-pane active show">
					  <table class="table table-dark table-sm small">
						  <thead>
							  <tr><th>Token</th><th>Wallet</th><th>Exchange</th></tr>
							</thead>
							<tbody>
							    <%= render partial: 'dapp/balances/ether_balances', locals: { dapp_status: dapp_status } %>
							</tbody>
						</table>
						<%= render partial: 'dapp/balances/new_ether_deposit_form' %>
						<table class="table table-dark table-sm small">
							<tbody>
								<%= render partial: 'dapp/balances/token_balances', locals: { dapp_status: dapp_status } %>
							</tbody>
						</table>
						<%= render partial: 'dapp/balances/new_token_deposit_form' %>
					</div>
		
					<div id='withdraw-form' role="tabpanel" aria-hidden="true" class="fade bg-dark tab-pane">
						<table class="table table-dark table-sm small">
							<thead>
								<tr><th>Token</th>
									<th>Wallet</th>
									<th>Exchange</th>
								</tr>
							</thead>
							<tbody>
						    <%= render partial: 'dapp/balances/withdraw_ether_balances', locals: { dapp_status: dapp_status } %>
							</tbody>
						</table>
					  <%= render partial: 'dapp/balances/new_ether_withdraw_form' %>
						<table class="table table-dark table-sm small">
							<tbody>
								<%= render partial: 'dapp/balances/withdraw_token_balances', locals: { dapp_status: dapp_status } %>
							</tbody>
						</table>
						<%= render partial: 'dapp/balances/new_token_withdraw_form' %>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="card bg-dark text-white">
		<div class="card-header">New Order</div>
		<div id='new-order-container' class="card-body">
			<div id='new-order'>
			<nav class="bg-dark text-white nav nav-tabs" role="tablist">
				<a href="#" role="tab" data-bs-toggle="tab" aria-selected="true" data-bs-target="#buy-order-container" class="nav-item nav-link active">Buy</a>
				<a id='sell-order-tab' href="#" role="tab" data-bs-toggle="tab" aria-selected="false" data-bs-target="#sell-order-container" class="nav-item nav-link">Sell</a>
	
			</nav>
			<div class="tab-content">
				<div id='buy-order-container' role="tabpanel" aria-hidden="false" class="fade bg-dark tab-pane active show">
					<%= render partial: 'dapp/balances/new_buy_order_form' %>
				</div>
				<div id='sell-order-container' role="tabpanel" aria-hidden="true" class="fade bg-dark tab-pane">
					<%= render partial: 'dapp/balances/new_sell_order_form' %>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/dapp/balances/_ether_balances.html.erb
<tr id='deposit-ether-balances'>
  <td>ETH</td>
  <td id='deposit-wallet-ether-balance'><%= format_decimals(dapp_status.ether_balance) %></td>
  <td id='deposit-exchange-ether-balance'><%= format_decimals(dapp_status.exchange_ether_balance) %></td>
</tr>

app/views/dapp/balances/_new_buy_order_form.html.erb
<%= form_tag orders_path, id: 'buy-order-form', data:{ controller: 'buy-order', action: 'submit->buy-order#submit'} do |f| %>
  <div class="form-group small w-100">
	  <label>Buy Amount (DAPP)</label>
	  <div class="input-group">
		  <%= text_field_tag :buy_amount, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: "Buy Amount", data: { buy_order_target: 'buyAmount'}  %>
	  </div>
  </div>
  <div class="form-group small w-100 pb-3">
	  <label>Buy Price</label>
	  <div class="input-group">
		  <%= text_field_tag :buy_price, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: "Buy Price", data: { buy_order_target: 'buyPrice'} %>
	  </div>
  </div>
  <%= submit_tag 'Buy Order', class: "btn btn-primary btn-sm btn-block w-100" %>
<% end %>

app/views/dapp/balances/_new_ether_deposit_form.html.erb
<%= form_tag deposits_path, class: 'row', id: 'ether-deposit-form', data:{ controller: 'ether-deposit', action: 'submit->ether-deposit#submit'}  do |f| %>
  <div class="col-12 col-sm pr-sm-2">
	  <%= text_field_tag :ether_amount, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: "ETH Amount", data: { ether_deposit_target: 'etherAmount'} %>
  </div>
  <div class="col-12 col-sm-auto pl-sm-0">
	  <%= submit_tag 'Deposit', class: 'btn btn-primary btn-block btn-sm' %>
  </div>
<% end %>

app/views/dapp/balances/_new_ether_withdraw_form.html.erb
<%= form_tag withdrawals_path, class: 'row', id: 'ether-withdraw-form', data:{ controller: 'ether-withdraw', action: 'submit->ether-withdraw#submit'} do |f| %>
	<div class="col-12 col-sm pr-sm-2">
		<%= text_field_tag  :ether_amount, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: "ETH Amount", data: { ether_withdraw_target: 'etherAmount'}%>
	</div>
	<div class="col-12 col-sm-auto pl-sm-0">
		<%= submit_tag 'Withdraw', class:  "btn btn-primary btn-block btn-sm"%>
	</div>
<% end %>

app/views/dapp/balances/_new_sell_order_form.html.erb
<%= form_tag sell_orders_path, id: 'sell-order-form', data:{ controller: 'sell-order', action: 'submit->sell-order#submit'} do |f| %>
	<div class="form-group small w-100">
		<label>Sell Amount (DAPP)</label>
		<div class="input-group">
			<%= text_field_tag  :sell_amount, nil, class:"form-control form-control-sm bg-dark text-white", placeholder:"Sell amount",
			data: { sell_order_target: 'sellAmount'}   %>
		</div>
	</div>
	<div class="form-group small w-100 pb-3">
		<label>Sell Price</label>
		<div class="input-group">
			<%= text_field_tag :sell_price, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: "Sell Price", data: { sell_order_target: 'sellPrice'} %>
		</div>
	</div>
	<%= submit_tag 'Sell Order',  class: "btn btn-primary btn-sm btn-block w-100" %>
<% end %>

app/views/dapp/balances/_new_token_deposit_form.html.erb
<%= form_tag token_deposits_path, class: 'row', id: 'token-deposit-form', data:{ controller: 'token-deposit', action: 'submit->token-deposit#submit'}  do |f| %>
	<div class="col-12 col-sm pr-sm-2">
		<%= text_field_tag :token_amount, nil, class: "form-control form-control-sm bg-dark text-white", placeholder: 'DAPP Amount', required: '', data: { token_deposit_target: 'tokenAmount'} %>
	</div>
	<div class="col-12 col-sm-auto pl-sm-0">
		<%= submit_tag 'Deposit', class: 'btn btn-primary btn-block btn-sm' %>
	</div>
<% end %>

app/views/dapp/balances/_new_token_withdraw_form.html.erb
<%= form_tag token_withdrawals_path, class: 'row', id: 'token-withdraw-form', data:{ controller: 'token-withdraw', action: 'submit->token-withdraw#submit'} do |f| %>
	<div class="col-12 col-sm pr-sm-2">
		<%= text_field_tag  :token_amount, nil, placeholder: "DAPP Amount", class: "form-control form-control-sm bg-dark text-white", data: { token_withdraw_target: 'tokenAmount'}  %>
	</div>
	<div class="col-12 col-sm-auto pl-sm-0">
		<%= submit_tag 'Withdraw', class: "btn btn-primary btn-block btn-sm" %>
	</div>
<% end %>

app/views/dapp/balances/_token_balances.html.erb
<tr id='deposit-token-balances'>
	<td>DAPP</td>
	<td id='deposit-wallet-token-balance'><%= format_token_balance(dapp_status.token_balance) %></td>
	<td id='deposit-exchange-token-balance'><%= format_token_balance(dapp_status.exchange_token_balance) %></td>
</tr>

app/views/dapp/balances/_token_ether_balances.html.erb
<tr id='token-ether-balances'>
  <td>ETH</td>
  <td><%= dapp_status.ether_balance %></td>
  <td><%= dapp_status.exchange_ether_balance %></td>
</tr>

app/views/dapp/balances/_withdraw_ether_balances.html.erb
<tr id='withdraw-ether-balances'>
  <td>ETH</td>
  <td id='withdraw-wallet-ether-balance'><%= format_decimals(dapp_status.ether_balance) %></td>
  <td id='withdraw-exchange-ether-balance'><%= format_decimals(dapp_status.exchange_ether_balance) %></td>
</tr>

app/views/dapp/balances/_withdraw_token_balances.html.erb
<tr id='withdraw-token-balances'>
	<td>DAPP</td>
	<td id='withdraw-wallet-token-balance'><%= format_token_balance(dapp_status.token_balance) %></td>
	<td id='withdraw-exchange-token-balance'><%= format_token_balance(dapp_status.exchange_token_balance) %></td>
</tr>