config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resource :dapp, only: [:show], controller: 'dapp'
  resource :account, only: [:show, :update], controller: 'account'
  resources :orders, only: [:create, :destroy, :update]
  resources :sell_orders, only: [:create]
  resources :deposits, only: [:create]
  resources :withdrawals, only: [:create]
  resources :token_deposits, only: [:create]
  resources :token_withdrawals, only: [:create]
  
  root to: 'dapp#show'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create    
    buy_order = Dapp::BuyOrder.new(transaction_hash: params[:transaction_hash])
    result = Blockchain::Runner.new(transaction: buy_order).run
    
    respond_to do |format|
     if result.success?
        format.turbo_stream {
          @order = result.response
        }
        format.html { redirect_to dapp_path, notice: 'Buy order successfully placed' }  
      else
        @error_message = result.error_message
        format.html { redirect_to dapp_path, notice: @error_message }
        format.turbo_stream { render 'shared/turbo_error' }
      end
    end
  end
  
  def update
    @order_id = order_id
    prev_token_price = params[:prev_token_price].to_d
    order_fill = Dapp::OrderFill.new(transaction_hash: params[:transaction_hash], prev_token_price: prev_token_price)
    result = Blockchain::Runner.new(transaction: order_fill).run

    respond_to do |format|
      if result.success?
        format.turbo_stream {
          @trade = result.response
          @dapp_status = Dapp::Status.new
        }
        format.html { redirect_to dapp_path, notice: 'Order successfully filled' }  
      else
        @error_message = result.error_message
        format.html { redirect_to dapp_path, notice: @error_message}
        format.turbo_stream { render 'shared/turbo_error' }
      end
    end
  end
  
  def destroy
    @order_id = order_id

    respond_to do |format|
      format.turbo_stream {}
      format.html { redirect_to dapp_path, notice: 'Order successfully cancelled' }  
    end
  end
  
  private
  
  def order_id
    params[:id].to_i
  end
end

app/views/orders/_buy_order.html.erb
<tr id="fill-order-<%= order.order_id %>" data-action="click->order-fill#click" data-controller="order-fill" data-toggle="tooltip" data-placement="right" title="Click here to sell" data-order-fill-url="<%= order_url(id: order.order_id) %>" data-order-fill-id="<%= order.order_id %>" class='order-book-order fill-order'>
  <td><%= order.token_amount %></td>
	<td class='text-success'><%= order.token_price %>
</td>
	<td><%= order.ether_amount %></td>
</tr>

app/views/orders/_my_order.html.erb
<tr id="my-order-<%= order.order_id %>" >
	<td class="<%= buy_or_sell_color(order.order_type) %>"><%= order.token_amount %></td>
	<td class="<%= buy_or_sell_color(order.order_type) %>"><%= order.token_price %></td>
	<td class="text-muted cancel-order text-danger" data-toggle="tooltip" data-placement="right" title="Click here to cancel" data-action="click->order-cancel#click" data-controller="order-cancel" data-order-cancel-id="<%= order.order_id %>" data-order-cancel-url="<%= order_url(id: order.order_id) %>">X</td>
</tr>

app/views/orders/_sell_order.html.erb
<tr id="fill-order-<%= order.order_id %>" data-action="click->order-fill#click" data-toggle="tooltip" data-placement="right" title="Click here to buy" data-controller="order-fill" data-order-fill-id="<%= order.order_id %>" data-order-fill-url="<%= order_url(id: order.order_id) %>" data-order-id="<%= order.order_id %>" class='order-book-order fill-order'>
  <td><%= order.token_amount %></td>
	<td class='text-danger'><%= order.token_price %></td>
	<td><%= order.ether_amount %></td>
</tr>

app/views/orders/cancel.turbo_stream.erb
<%= turbo_stream.remove("my-order-#{@order_id}") %>

<%= turbo_stream.remove("fill-order-#{@order_id}") %>

<%= turbo_stream.append "toasts", 
												partial: "shared/toast", 
												locals: { message: "Order successfully cancelled", 
													notice_at: @notice_at } %>

app/views/orders/create.turbo_stream.erb
<%= turbo_stream.prepend('my-orders-list',
                          partial: "orders/my_order",
                          locals: { 
                            order: @order
													}) %>
													
<%= turbo_stream.append('order-book',
                          partial: "orders/buy_order",
                          locals: { 
                            order: @order
													}) %>
																		
<%= turbo_stream.replace('buy-order-form',
                          partial: "dapp/balances/new_buy_order_form") %>
													
<%= turbo_stream.append "toasts", partial: "shared/toast", locals: { message: "Buy order successfully placed" } %>

app/views/orders/destroy.turbo_stream.erb
<%= turbo_stream.remove("my-order-#{@order_id}") %>

<%= turbo_stream.remove("fill-order-#{@order_id}") %>

<%= turbo_stream.append "toasts", 
												partial: "shared/toast", 
												locals: { message: "Order successfully cancelled" } %>

app/views/orders/fill.turbo_stream.erb
<%= turbo_stream.replace('ether-balances',
                          partial: "dapp/balances/ether_balances",
                          locals: { 
                           dapp_status: @dapp_status
													}) %>
													
<%= turbo_stream.replace('withdraw-ether-balances',
                          partial: "dapp/balances/withdraw_ether_balances",
                          locals: { 
                           dapp_status: @dapp_status
													}) %>

<%= turbo_stream.remove("fill-order-#{@order_id}") %>
<%= turbo_stream.remove("my-order-#{@order_id}") %>

<%= turbo_stream.append('my-trades-list',
                          partial: "accounts/my_trade",
                          locals: { 
                            trade: @trade
													}) %>
													
<%= turbo_stream.prepend('all-trades-list',
                          partial: "accounts/trade",
                          locals: { 
                            trade: @trade
													}) %>
													
<%= turbo_stream.append "toasts", 
												partial: "shared/toast", 
												locals: { message: "Order successfully filled ", 
													notice_at: @trade.formatted_timestamp } %>

app/views/orders/update.turbo_stream.erb
<%= turbo_stream.replace('ether-balances',
                          partial: "dapp/balances/ether_balances",
                          locals: { 
                           dapp_status: @dapp_status
													}) %>
													
<%= turbo_stream.replace('withdraw-ether-balances',
                          partial: "dapp/balances/withdraw_ether_balances",
                          locals: { 
                           dapp_status: @dapp_status
													}) %>

<%= turbo_stream.remove("fill-order-#{@order_id}") %>
<%= turbo_stream.remove("my-order-#{@order_id}") %>

<%= turbo_stream.prepend('my-trades-list',
                          partial: "dapp/my_trade",
                          locals: { 
                            trade: @trade
													}) %>
													
<%= turbo_stream.prepend('all-trades-list',
                          partial: "dapp/trade",
                          locals: { 
                            trade: @trade
													}) %>
													
<%= turbo_stream.append "toasts", 
												partial: "shared/toast", 
												locals: { message: "Order successfully filled ", 
													notice_at: @trade.formatted_timestamp } %>