config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resource :dapp, only: [:show], controller: 'dapp'
  resource :account, only: [:show, :update], controller: 'account'
  resources :orders, only: [:create, :destroy, :update]
  resources :sell_orders, only: [:create]
  resources :deposits, only: [:create]
  resources :withdrawals, only: [:create]
  resources :token_deposits, only: [:create]
  resources :token_withdrawals, only: [:create]
  
  root to: 'dapp#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockchainDeveloperBootcampRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/web3/1.5.2/web3.min.js"></script>

	 <%= stylesheet_link_tag 'application', media: 'all' %>
	 <%= stylesheet_pack_tag 'application', media: 'all' %>
	 <%= javascript_pack_tag 'application' %>
	 
	 <%= javascript_tag do %>
	   window._exchange_contract_address = "<%= ENV['EXCHANGE_CONTRACT_ADDRESS'] %>"
		 window._block_chain_url = "<%= ENV['BLOCKHAIN_URL'] %>"
	 <% end %>
  </head>

  <body>
	  <div id='root'>
		  <div>
				<div data-controller="load" data-load-success-url='<%= account_path %>' data-load-error-url='<%= account_path %>'></div>
				
		    <%= render partial: 'shared/notices' %>
				<%= render partial: 'shared/header' %>
				<%= render partial: 'shared/toasts' %>
				
				<div class='content'>
				  <%= yield %>
				</div>
					
			</div>
		</div>
		
  </body>
</html>